feat: support native listener in Vue 3
ecomfe/vue-echarts pull request #767
Opened 2024-02-29 07:13 UTC by kingyue737

Successor of #765

2024-02-29 07:39 UTC, Justineo requested changes

2024-02-29 07:39 UTC, Justineo commented on src/ECharts.ts
> +        : { ...this.nonEventAttrs, ...this.nativeEventAttrs }
I think we can make `native:click` also work in Vue 2.

2024-04-22 04:18 UTC, Justineo requested changes

2024-04-22 04:18 UTC, Justineo commented on src/ECharts.ts
> +          }
We should remove `native:` events from `realListeners`. (We probably should shallow clone it at https://github.com/ecomfe/vue-echarts/pull/767/files#diff-6075537841e7fc013c5db4e243e71a7df65a1c92f205aa8d6151f4df666a07a4R118 first.)

I think we'd better match event names against a regexp like `/^[~!&]*native:/`.

2024-04-22 10:43 UTC, kingyue737 commented on src/ECharts.ts
> +          }
I found that the order of `.passive` `.capture` and `.once` is fixed and the prefix of each modifier will only appear once no matter how many times the users added it.

2024-04-22 11:21 UTC, Justineo approved these changes

2024-04-22 11:22 UTC, merged